# Generated by Django 4.2 on 2025-03-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brand', 'Brand'), ('scent_family', 'Scent Family'), ('longevity', 'Longevity'), ('gender', 'Gender'), ('note', 'Fragrance Note')], max_length=20, verbose_name='Category')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Enum Configuration',
                'verbose_name_plural': 'Enum Configurations',
                'ordering': ['category', 'sort_order', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('best_for', models.TextField(blank=True, verbose_name='Best For')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(limit_choices_to={'category': 'brand'}, on_delete=django.db.models.deletion.PROTECT, related_name='brand_perfumes', to='perfumes.enumconfig', verbose_name='Brand')),
                ('gender', models.ForeignKey(limit_choices_to={'category': 'gender'}, on_delete=django.db.models.deletion.PROTECT, related_name='gender_perfumes', to='perfumes.enumconfig', verbose_name='Gender')),
                ('key_notes', models.ManyToManyField(limit_choices_to={'category': 'note'}, related_name='note_perfumes', to='perfumes.enumconfig', verbose_name='Key Notes')),
                ('longevity', models.ForeignKey(limit_choices_to={'category': 'longevity'}, on_delete=django.db.models.deletion.PROTECT, related_name='longevity_perfumes', to='perfumes.enumconfig', verbose_name='Longevity')),
                ('scent_family', models.ForeignKey(limit_choices_to={'category': 'scent_family'}, on_delete=django.db.models.deletion.PROTECT, related_name='scent_perfumes', to='perfumes.enumconfig', verbose_name='Scent Family')),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
