# Generated by Django 4.2 on 2025-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='price',
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
